### PR TITLE
Facilitate dockerized CoatRack deployment, remove dependencies on external Git service and external CoatRack gateway jar

### LINKED ISSUE #167: The proxy jar file should be included in the admin docker image
Currently, the proxy template is obtained by contacting a web server, which stores a proxy template that could possibly be deprecated and thus possibly does not work with the running Admin version. To keep Admin and Gateway versions compatible and up-to-date, the build scripts in the root folder should be modified in a way, that the admin docker image will also contain a freshly compiled proxy image which admin can access directly.

It will probably make sense to handle this issue as a follow-up issue of #162.

### PR DESCRIPTION
**Pull request by ChristophBaierATB**
### Bugfixes and features
This PR covers several issues and features:
* The Gateway creation was fixed by getting rid the external bitbucket service dependency, see #186. The Gateway configuration files are now stored locally when IDE/CLI is uesed or within a docker volume when docker-compose is used for deployment. 
* The proxy jar is now stored locally as well instead of pulling it from an external server, see #167. 
* For developers: CoatRack Web Application and Config Server can be started via IDE or CLI without requiring any pre-configuration or active profiles. They work out of the box now. The Web Application will use the proxy jar file generated by the maven build process. See #184 and #172.
* A full CoatRack instance with DB can theoretically easily be deployed using the CoatRack images from Dockerhub as soon as the images of this branch are pushed, see README and #162. Because of that, this feature could not be tested yet. We should discuss that first.

I also added some documentation as new sections in README.md: "Installation using Docker Images" (not working because this PR is not merged yet and master has gateway creation problems because it still depends on the broken bitbucket service) and "Operations from Scratch".

### How to test this PR
* First approach: If not existent, build CoatRack to create the file `/spring-boot/proxy/target/<proxy>.jar`. This can be achieved by executing the `build.sh` file in the project directory. Please try to run CoatRack via simply starting the Web Application/Admin and Config server via IDE or CLI without any active profile and check if it works for you.
* Second approach: Go to the "docker" folder and run `bash build-and-deploy-images-locally.sh'. A full, dockerized CoatRack instance should be set up.

Especially test if the gateway creation, download, deployment and service-call-via-api-key feature are working correctly for you.

closes #167, #184, #172, #162, #186 

### TODO for me before merging
 - [x] Add a script that builds starts admin and one that starts config-server. Starting a component should not depend on the IDE.
 - [x]  Discuss if I can push the images of this branch to the Dockerhub repository to test the use cases from the section of the  README.md: "Installation using Docker Images".
 - [x] The Pipeline failed. Probably because I moved some scripts to the `docker` folder. To be fixed. -> I solved that by putting this folder from the "target" directory to the project directory.

### CODE REVIEW

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+    @PostConstruct
+    private void emptyProxyConfigFilesFolderIfExistsForNonDockerComposeDeployments() throws IOException {
+        if (!isDockerComposeSetup){
+            Path targetFolderPath = Paths.get(System.getProperty("user.dir") + "/target");
+            if (Files.notExists(targetFolderPath))
+                Files.createDirectory(targetFolderPath);
+
+            Path gatewayConfigFilesFolderPath = Paths.get(gatewayConfigFilesFolderLocation);
+            if (Files.exists(gatewayConfigFilesFolderPath)){
+                FileUtils.deleteDirectory(gatewayConfigFilesFolderPath.toFile());
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:64]: If I understand correctly, CoatRack deletes something from my hard drive on every start-up. Does not seem like a good idea to me, as it could in some situations delete important stuff by accident. To be discussed.

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:64]: If I understand correctly, CoatRack deletes something from my hard drive on every start-up. Does not seem like a good idea to me, as it could in some situations delete important stuff by accident. To be discussed.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+    @Value("${ygg.admin.api-base-url-for-gateway}")
+    private String adminApiBaseUrlForGateway;
+
+    @Value("${is-run-via-docker-compose-setup}")
+    private boolean isDockerComposeSetup;
+
+    @PostConstruct
+    private void emptyProxyConfigFilesFolderIfExistsForNonDockerComposeDeployments() throws IOException {
+        if (!isDockerComposeSetup){
+            Path targetFolderPath = Paths.get(System.getProperty("user.dir") + "/target");
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:58]: The term "target" is unclear to me here. What will that folder be used for?

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:58]: The term "target" is unclear to me here. What will that folder be used for?

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+        Path gatewayConfigFileToBeDeletedPath = Paths.get(gatewayConfigFilesFolderLocation + "/ygg-proxy-" + proxy.getId() + ".yml");
+        if (Files.exists(gatewayConfigFileToBeDeletedPath)) {
+            tryToDeleteGatewayConfigFile(proxy, gatewayConfigFileToBeDeletedPath);
+        } else {
+            throw new FileNotFoundException("Tried to delete the configuration file for proxy " + proxy.getId()
+                    + ", but there is no according file + " + gatewayConfigFileToBeDeletedPath);
+        }
+    }
+
+    private void tryToDeleteGatewayConfigFile(Proxy proxy, Path gatewayConfigFileToBeDeletedPath) throws IOException {
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:95]: This method does not really need the proxy object, just uses it for logging. Thus maybe remove this parameter?

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:95]: This method does not really need the proxy object, just uses it for logging. Thus maybe remove this parameter?

File: spring-boot/admin/src/main/resources/application.yml [hunk 4]
```diff
@@ -12,7 +12,8 @@ logging:
 ygg:
   mail:
     # Define if CoatRack should send verification emails to newly registered users
-    verify-new-users-via-mail: true
+    # TODO Feature is not working, yet. After #53 is fixed, the parameter can be set to "true".
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:15]: I am pretty sure that feature works fine, I used it in the past. However, I agree it probably makes sense to switch it off in the default setting, because for local dev testing of CoatRack the verification feature is not required in most cases.

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:15]: I am pretty sure that feature works fine, I used it in the past. However, I agree it probably makes sense to switch it off in the default setting, because for local dev testing of CoatRack the verification feature is not required in most cases.

File: spring-boot/admin/src/main/resources/application.yml [hunk 5]
```diff
@@ -25,7 +26,14 @@ ygg:
     verification.server.url: http://localhost:8080
 
   admin:
-    database.insertSampleDataOnStartup: true
+    database:
+      # Define if you want to use development test data to be generated by CoatRack on startup
+      insertSampleDataOnStartup: true
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:31]: To be discussed: we should probably set this to "false" for the default config. For someone new to CoatRack that data will probably be confusing.

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:31]: To be discussed: we should probably set this to "false" for the default config. For someone new to CoatRack that data will probably be confusing.

File: spring-boot/admin/src/main/resources/application.yml [hunk 6]
```diff
@@ -49,14 +57,16 @@ ygg:
...
+          # Provider and identifier of the service to be used in the getting started tutorial for service users
+          provider.username: tutorial-service-provider-github-username
+          uriIdentifier: humidity-by-locations
   proxy:
     executable-jar:
       generated.path: /tmp
-      # URL of the "template jar" that CoatRack uses as basis to generate proxies (without the trailing version number and .jar filename extension)
-      template.url: https://www.kyoe.es/proxies/coatrack-proxy-
+      # URL of the "template jar" that CoatRack uses as basis to generate proxies.
+      # During development testing, this should usually point to your locally built ygg-proxy.jar
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:67]:
```suggestion
      # During development testing, this should usually point to your locally built coatrack-gateway.jar
```

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:67]:
```suggestion
      # During development testing, this should usually point to your locally built coatrack-gateway.jar
```

File: spring-boot/admin/src/main/resources/application.yml [hunk 7]
```diff
@@ -76,6 +86,14 @@ spring:
   data:
     rest:
       base-path: /api
+  thymeleaf:
+    # Enables reloading of thymeleaf templates on runtime using IntelliJ
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:90]: We should not put IDE-specific settings in the general config file. Could maybe be put into the "private profile template file".

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:90]: We should not put IDE-specific settings in the general config file.

File: spring-boot/admin/src/main/resources/application.yml [hunk 8]
```diff
@@ -107,3 +125,11 @@ security:
...
 
 management.security.enabled: false
+
+# Proxy configuration files are stored in this directory. The value of this parameter needs to direct to the same
+# folder as spring.cloud.config.server.native.searchLocations from the Config Servers application.yml.
+proxy.config.files.folder: ${user.dir}/target/temp-gateway-config-file-storage
+
+# If CoatRack is deployed via IDE/commandline the Gateway config files will be stored in the 'target' folder of the
+# project. If docker-compose is used for deployment, these files will be stored internally within a docker volume.
+is-run-via-docker-compose-setup: false
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:135]: This is a default yml config that will be put inside the admin jar file. That jar can be run on its own but it could also be put into a container and be run via docker-compose. 

Therefore I think we simply cannot know here if it is running in a docker-compose setup, so we should not define this parameter here. It could lead to unexpected problems in specific deployment situations.

Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:135]: This is a default yml config that will be put inside the admin jar file. That jar can be run on its own but it could also be put into a container and be run via docker-compose. 

Therefore I think we simply cannot know here if it is running in a docker-compose setup, so we should not define this parameter here. It could lead to unexpected problems in specific deployment situations.

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+import javax.annotation.PostConstruct;
+
+/**
+ *
+ * @author perezdf, ChristophBaier
+ */
+
+@Slf4j
+@Component
+public class GatewayConfigFilesStorage {
```
[the remark this answers is not in the document]
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:44]: Or maybe simply: `GatewayConfigFilesService`?

**Comment by BrunoSilvaATB** [comment]
image

File: README.md [hunk 10]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+
+ The following prerequisites are required:
+
+*  a Linux shell - Windows users can use WSL of the Git Bash shell instead
+*  docker
+*  docker-compose
+
+
+
+### Deployment For Newcomers
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:71]: I agree. "Newcomers" addresses the wrong group. It should be a word that addresses people who are familiar with CoatRack basic functionality and like to deploy and test it for their first time.

File: README.md [hunk 11]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+
+This approach is suggested if you are completely new to CoatRack and want to just want to experience what it actually does. Follow these instructions:
+
+1. Change the `INSERT_SAMPLE_DATA_ON_STARTUP` parameter in `.env` to `true` to initialize the example Gateway in the database.
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:75]: I agree. I could maybe create a script that is to be executed for that purpose. Just one command should be required to make it as easy as possible.

File: README.md [hunk 12]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+CoatRack will be accessible at `localhost:8080`. The 'database-initialization' has to be performed only once at the beginning. The initialization will persist on the docker volume used by the database.
+
+
+
+## Operations from Scratch
+
+To build CoatRack from scratch the following prerequisites are required in addition to the dependencies mentioned in the previous section:
+
+* OpenJDK 11
+* Maven 3.6.3 or higher
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:127]: Yes. Therefore I wrote "in addition to the dependencies mentioned in the previous section". Maybe its too abstract and I should just list them here explicitly as well.

File: docker/docker-compose-deployment/initialize-databases-if-necessary.sh [hunk 13]
```diff
@@ -0,0 +1,23 @@
...
+  -v "${DATABASE_VOLUME}":/var/lib/postgresql/data \
+  -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
+  postgres:"${POSTGRES_VERSION}"
+
+echo "  Waiting a few seconds until database is ready."
+sleep 5
+
+echo "  Create databases 'coatrack' and 'ygg_config_server' in PostgreSQL."
+docker exec "${DATABASE_CONTAINER_NAME}" psql -U postgres -c "create database coatrack;"
+docker exec "${DATABASE_CONTAINER_NAME}" psql -U postgres -c "create database ygg_config_server;"
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/initialize-databases-if-necessary.sh:20]: We should also rename "coatrack" database to "coatrack_web_application".

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 2 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: "target" was removed due to pipeline issues. I think the thread can be closed.

File: spring-boot/admin/src/main/resources/application.yml (hunk 8 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:135]: To be discussed.

File: build-docker.sh [hunk 14]
```diff
@@ -1,10 +0,0 @@
-#!/bin/bash
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply build-docker.sh:1]: To be discussed.

File: docker/Dockerfile [hunk 15]
```diff
@@ -0,0 +1,32 @@
...
+ENV CONTAINER_HOME_DIR="/home/coatrack"
+ENV CONTAINER_JAR_FILES_DIR="/home/coatrack/jars"
+ENV CONTAINER_GATEWAY_CONFIG_FILES_DIR="/home/coatrack/proxy-config-files"
+
+# Copy the module jar to be executed into the docker container.
+COPY ${PROJECT_FOLDER_MODULE_TARGET_DIR}/${COATRACK_MODULE_JAR} ${CONTAINER_JAR_FILES_DIR}/${COATRACK_MODULE_JAR}
+
+# Only the config server does not require a gateway jar file.
+COPY ${PROJECT_FOLDER_GATEWAY_TARGET_DIR}/${COATRACK_GATEWAY_JAR} ${CONTAINER_JAR_FILES_DIR}/${COATRACK_GATEWAY_JAR}
+RUN if [ ${MODULE} == "config-server" ]; then rm ${CONTAINER_JAR_FILES_DIR}/${COATRACK_GATEWAY_JAR}; fi
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/Dockerfile:25]: To be discussed.

File: docker/Dockerfile [hunk 16]
```diff
@@ -0,0 +1,32 @@
+FROM adoptopenjdk/openjdk11:jre-11.0.14_9-alpine
+LABEL maintainer=coatrack.eu
+
+ARG MODULE
+ARG PROJECT_VERSION
+
+# File names.
+ENV COATRACK_MODULE_JAR="coatrack-${MODULE}-${PROJECT_VERSION}.jar"
+ENV COATRACK_GATEWAY_JAR="coatrack-proxy-${PROJECT_VERSION}.jar"
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/Dockerfile:9]: To be discussed.

File: README.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:75]: Note for me: Is it possible to override a variable from .env file by defining a custom environment variable using an "example-setup" profile?

File: README.md [hunk 17]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+
+
+
+### Deployment for Production
+
+This approach is meant for developers and people who would like to deploy a production-ready CoatRack instance with a clean, empty database and without an Example-Gateway. Just go to the directory `docker-compose-deployment` and execute:
+
+```sh
+bash initialize-databases-if-necessary.sh
+docker-compose up -d
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:115]: This approach pull the latest images build on master and not this branch. The instruction should work, when we merge this branch and push the images to Dockerhub.

File: README.md [hunk 18]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+
+* OpenJDK 11
+* Maven 3.6.3 or higher
+
+
+
+There are two scripts in the `docker` directory helping you:
+
+* `build-and-push-images.sh` builds the docker image of each CoatRack modul from source and pushes the images to Dockerhub. This only works, when the docker daemon is already logged in to the CoatRack repository. This script is especially useful within a CI pipeline to update the latest Dockerhub images.
+* `build-and-deploy-images-locally.sh` also builds the above mentioned docker images from scratch for local use and deploys a production-ready instance locally using these images. This is especially useful for developers who apply changes to the source code locally and want to test the impact of these changes in a realistic setup.
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:134]: Done as suggested.

File: README.md (hunk 10 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:71]: I changed it to "First Example Deployment" and stating "This approach is suggested if you are familiar with the basic CoatRack functionality provided by [[coatrack.eu](https://coatrack.eu/)](https://coatrack.eu)" ... This is what I originally meant.

File: README.md [hunk 19]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
 
-Scripts for building and running CoatRack are available in the root folder of the code base. To build CoatRack, use:
 
-```console
-./build.sh
+## Installation using production-ready Docker Images
+
+ The following prerequisites are required:
+
+*  a Linux shell - Windows users can use WSL of the Git Bash shell instead
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:65]: Done as suggested.

File: README.md [hunk 20]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+2. Go to the directory `docker/docker-compose-deployment` and execute:
+
+```sh
+bash initialize-databases-if-necessary.sh
 ```
-To run the CoatRack web application, use:
 
-```console
-./run-admin-application.sh
+* The previous step is required to create the databases within PostgreSQL. Now you can set up CoatRack via:
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:82]: Done. I changed that as suggested but putting it in a line before the actual comment.

File: README.md [hunk 21]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+* The last step is to check out the service provided by the example Gateway. Search for this URL in your browser:
 
-```console
-./run-admin-application.sh [optional-spring-profile-name]
+```http
+http://localhost:8088/humidity-by-location?api-key=ee11ee22-ee33-ee44-ee55-ee66ee77ee88
 ```
-To create your personal custom Spring profile for CoatRack, please follow the instructions in the following template file:
+
+* The Example-Gateway should accept the provided API key and redirect you to the website of the `humidity-by-location` service.
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:94]: See comment above. The wording "Newcomer" was wrong. This setup is meant for people who already know the basic functionality of CoatRack. I also changed that in the description.

File: README.md [hunk 22]
```diff
@@ -52,29 +56,85 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+To build CoatRack from scratch the following prerequisites are required in addition to the dependencies mentioned in the previous section:
+
+* OpenJDK 11
+* Maven 3.6.3 or higher
+
+
+
+There are two scripts in the `docker` directory helping you:
+
+* `build-and-push-images.sh` builds the docker image of each CoatRack modul from source and pushes the images to Dockerhub. This only works, when the docker daemon is already logged in to the CoatRack repository. This script is especially useful within a CI pipeline to update the latest Dockerhub images.
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:133]: I changed that so it states that this script shall be used by the CI pipeline only.

File: README.md (hunk 12 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md:127]: Done as suggested in my comment.

File: README.md (hunk 17 above)
[the remark this answers is not in the document]
Comment (gr-hovest-atb) [reply README.md:115]: Should we then maybe move these instructions to a follow-up issue, so that can first merge this PR (without these instructions), then we can test these instructions properly before merging? This way we prevent that the master README contains instructions that have not yet been fully tested.

File: README.md [hunk 23]
```diff
@@ -58,34 +58,34 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
 
-### Deployment For Newcomers
+### First Example Deployment
 
-This approach is suggested if you are completely new to CoatRack and want to just want to experience what it actually does. Follow these instructions:
+This approach is suggested if you are familiar with the basic CoatRack functionality provided by [coatrack.eu](https://coatrack.eu) and you want to deploy your own CoatRack instance. Go to the directory `docker/docker-compose-deployment` and follow these instructions:
 
-1. Change the `INSERT_SAMPLE_DATA_ON_STARTUP` parameter in `.env` to `true` to initialize the example Gateway in the database.
-2. Go to the directory `docker/docker-compose-deployment` and execute:
+1. Change the `INSERT_SAMPLE_DATA_ON_STARTUP` parameter in `.env` to `true` to initialize some example data. This step is optional.
```
Comment (gr-hovest-atb) [inline README.md:75]: If the sample data is not included, the access to the sample service via the sample gateway will probably not work. So I am not sure if this makes sense.

File: README.md [hunk 24]
```diff
@@ -106,32 +106,35 @@ bash stop-containers-and-clean-up-traces-if-existent.sh
 
 
 
-### Deployment for Production
+### Regular Deployment
 
-This approach is meant for developers and people who would like to deploy a production-ready CoatRack instance with a clean, empty database and without an Example-Gateway. Just go to the directory `docker-compose-deployment` and execute:
+This approach is meant for developers and people who would like to deploy a CoatRack instance with a clean, empty database and without an Example-Gateway. Just go to the directory `docker-compose-deployment` and execute:
```
Comment (gr-hovest-atb) [inline README.md:111]:
```suggestion
This approach is meant for those who would like to deploy a new CoatRack instance with a clean, empty database. Just go to the directory `docker-compose-deployment` and execute:
```

File: README.md [hunk 25]
```diff
@@ -58,34 +58,34 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
 *  docker
 *  docker-compose
 
 
 
-### Deployment For Newcomers
+### First Example Deployment
 
-This approach is suggested if you are completely new to CoatRack and want to just want to experience what it actually does. Follow these instructions:
+This approach is suggested if you are familiar with the basic CoatRack functionality provided by [coatrack.eu](https://coatrack.eu) and you want to deploy your own CoatRack instance. Go to the directory `docker/docker-compose-deployment` and follow these instructions:
```
Comment (gr-hovest-atb) [inline README.md:73]: Maybe mention that this is an experimental or test deployment?

File: build-docker.sh (hunk 14 above)
[the remark this answers is not in the document]
Comment (gr-hovest-atb) [reply build-docker.sh:1]: As discussed: This pull request should include a change in the pipeline configuration, so that it will build after merging.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 1 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:60]: It is okay for an application to create files/folders on start-up, but most people would not expect it to delete files. Will it lead to problems if we keep that directory?

File: README.md (hunk 25 above)
Comment (ChristophBaierATB) [reply README.md]: As discussed, I just removed this section from the README for now and saved your suggestions for later when all features are working and this section could be re-added.

File: README.md (hunk 24 above)
Comment (ChristophBaierATB) [reply README.md]: As discussed, I just removed this section from the README for now and saved your suggestions for later when all features are working and this section could be re-added.

File: README.md (hunk 23 above)
Comment (ChristophBaierATB) [reply README.md]: You are correct which is why I corrected that. I also introduced a simple bash script which can be run, to set up the example instance of CoatRack using example data and an example gateway.

File: spring-boot/admin/src/main/resources/application.yml (hunk 8 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:135]: I changed the parameter name to `is-gateway-config-files-folder-in-users-home-directory` which is much more fitting than the old name.

You can either run the Admin jar via IDE/CLI which works because of the default value of this parameter in the default profile. Your second option is to run it using the docker-compose.yml which overrides this parameter inverses its value. As far as I know, there are no other deployment options, so where do you see possible problems?

File: spring-boot/admin/src/main/resources/application.yml (hunk 7 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:90]: Actually, only the comment is IDE specific, the configuration is not so I just removed the "using IntelliJ" part. 

I would like to keep that in the default yml to have a nice out-of-the-box working setup for developers which enables resource reloading, especially for frontend works. I don't see a disadvantage in this approach, yet. Do you see any?

File: README.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md]: Solved. The section is temporarily removed (see comments below) and a script for very easy example setup deployment was created.

File: README.md (hunk 17 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply README.md]: Done as suggested. See comments below.

File: build-docker.sh (hunk 14 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply build-docker.sh:1]: I adapted the according line in `.github/workflows/maven.yml` to:
```sh
run: cd docker && bash build-and-push-images.sh
```

[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply build-docker.sh:1]: As discussed we want to merge this PR to see if the pipeline works correctly.

File: Dockerfile [hunk 26]
```diff
@@ -1,13 +0,0 @@
-FROM alpine:edge
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply Dockerfile:1]: See comment above.

File: build-push-docker-image.sh [hunk 27]
```diff
@@ -1,10 +0,0 @@
-#!/bin/bash
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply build-push-docker-image.sh:1]: See comment above.

[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply build-push-docker-image.sh:1]: The building logic was shifted to `docker/build-and-push-images.sh` which should take care of everything.

File: docker/Dockerfile (hunk 16 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/Dockerfile]: I refactored the whole image building logic. Please re-review the code.

File: docker/Dockerfile (hunk 15 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/Dockerfile]: See comment above.

File: docker/Dockerfile [hunk 28]
```diff
@@ -0,0 +1,32 @@
...
+ENV CONTAINER_GATEWAY_CONFIG_FILES_DIR="/home/coatrack/proxy-config-files"
+
+# Copy the module jar to be executed into the docker container.
+COPY ${PROJECT_FOLDER_MODULE_TARGET_DIR}/${COATRACK_MODULE_JAR} ${CONTAINER_JAR_FILES_DIR}/${COATRACK_MODULE_JAR}
+
+# Only the config server does not require a gateway jar file.
+COPY ${PROJECT_FOLDER_GATEWAY_TARGET_DIR}/${COATRACK_GATEWAY_JAR} ${CONTAINER_JAR_FILES_DIR}/${COATRACK_GATEWAY_JAR}
+RUN if [ ${MODULE} == "config-server" ]; then rm ${CONTAINER_JAR_FILES_DIR}/${COATRACK_GATEWAY_JAR}; fi
+
+# Security improvements.
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/Dockerfile]: See comment above.

File: docker/docker-compose-deployment/.env [hunk 29]
```diff
@@ -0,0 +1,21 @@
+TAG=2.0.0-SNAPSHOT
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/.env:1]: We discussed to keep it as it is for now. If changes are required we will do that in another PR, maybe by solving #192.

File: docker/docker-compose-deployment/.env [hunk 30]
```diff
@@ -0,0 +1,21 @@
...
+DATABASE_VOLUME=coatrack-database-volume
+DATABASE_CONTAINER_NAME=coatrack-database
+
+CONFIG_SERVER_CONTAINER_NAME=coatrack-config-server
+CONFIG_SERVER_USERNAME=insert-config-server-username-here
+CONFIG_SERVER_PASSWORD=insert-config-server-password-here
+
+ADMIN_CONTAINER_NAME=coatrack-admin
+
+PROXY_CONFIG_FILES_VOLUME=coatrack-proxy-config-files-volume
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/.env]: Done as suggested.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 1 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java:60]: This directory is ignored by git. It contains only Gateway Config Files created when running CoatRack via CLI/IDE without using docker which is only performed by developers. Therefore, to keep this directory small and clean, it is emptied on every startup. 

This cleanup will not affect the persistence of Gateway Config File docker volume. I don't see any problems here, yet.

File: docker/docker-compose-deployment/initialize-databases-if-necessary.sh [hunk 31]
```diff
@@ -0,0 +1,23 @@
...
+  --name "${DATABASE_CONTAINER_NAME}" \
+  -v "${DATABASE_VOLUME}":/var/lib/postgresql/data \
+  -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
+  postgres:"${POSTGRES_VERSION}"
+
+echo "  Waiting a few seconds until database is ready."
+sleep 5
+
+echo "  Create databases 'coatrack' and 'ygg_config_server' in PostgreSQL."
+docker exec "${DATABASE_CONTAINER_NAME}" psql -U postgres -c "create database coatrack;"
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/initialize-databases-if-necessary.sh]: Done, see comment above.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: Done as suggested.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 3 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: Done.

File: spring-boot/admin/src/main/resources/application.yml (hunk 4 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:15]: So, we can leave it as it is?

File: spring-boot/admin/src/main/resources/application.yml (hunk 6 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Done as suggested.

File: docker/docker-compose-deployment/docker-compose.yml [hunk 32]
```diff
@@ -0,0 +1,77 @@
...
+      --ygg.admin.database.insertSampleDataOnStartup=${INSERT_SAMPLE_DATA_ON_STARTUP} \
+      --ygg.proxy.generate-bootstrap-properties.spring.cloud.config.uri=http://localhost:8998 \
+      --spring.cloud.config.uri=http://${CONFIG_SERVER_CONTAINER_NAME}:8998 \
+      --spring.cloud.config.username=${CONFIG_SERVER_USERNAME} \
+      --spring.cloud.config.password=${CONFIG_SERVER_PASSWORD} \
+      --ygg.proxy.executable-jar.template.url=file://${JAR_DIR}/coatrack-proxy- \
+      --proxy.config.files.folder=${PROXY_CONFIG_FILES_FOLDER} \
+      --is-run-via-docker-compose-setup=true"]
+
+  coatrack-example-gateway:
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/docker-compose.yml:58]: This is actually used for the example-deployment tutorial which is not documented yet, because I removed that section from the README. We wanted to add it later, when this PR is merged and the deployment of your own CoatRack instance using dockerhub images works.

File: docker/docker-compose-deployment/initialize-databases-if-necessary.sh [hunk 33]
```diff
@@ -0,0 +1,23 @@
...
+
+echo "  Starting database."
+docker run --rm -d \
+  --name "${DATABASE_CONTAINER_NAME}" \
+  -v "${DATABASE_VOLUME}":/var/lib/postgresql/data \
+  -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
+  postgres:"${POSTGRES_VERSION}"
+
+echo "  Waiting a few seconds until database is ready."
+sleep 5
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/initialize-databases-if-necessary.sh]: I also found this article interesting: https://docs.docker.com/compose/startup-order/

Best practice would be to implement logic in our application to wait. Probably this can be configured quite easily by setting the correct configuration for hibernate in the application.yml.

[the remark this answers is not in the document]
Comment (gr-hovest-atb) [reply docker/docker-compose-deployment/initialize-databases-if-necessary.sh]: Could be moved to a follow-up issue.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 1 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: If this is only to be used during development, then I would suggest to remove it from the code and move it to some script that developers use to run the application locally (or to move it to a cleanup script that developers can optionally use).

In doubt we should have another discussion about this. The main problem I see here is: if I understand correctly, starting up the application will delete stuff from a _previous_ run of the application, which is not at all relevant for the current run. This should imho not happen, as maybe for some reason (e.g. tests) developers would want to keep files from the previous run (and usually you do not expect that a new run will delete stuff from a previous run, except maybe for log files).

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 3 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: My main point was just regarding separation of concerns: if a method does not need a parameter, why pass it to the method?

If you want it logged, maybe put the logging in the place where this method is called? And if you want it in the error message, maybe create the error message in the place where you call this method?

But this is just a suggestion, if you consider the current solution better, feel free to keep it as it is.

File: spring-boot/admin/src/main/resources/application.yml (hunk 4 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/resources/application.yml:15]: You can leave the setting as false, that is fine.

But please remove the TODO comment, as it is wrong. It says "Feature is not working", and that is not true

File: spring-boot/admin/src/main/resources/application.yml (hunk 5 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/resources/application.yml:32]: Yes, we should create a follow-up.

File: spring-boot/admin/src/main/resources/application.yml (hunk 7 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/resources/application.yml]: If this is just for developers, maybe move it to the private application yml template? You would not want this setting for a normal installation.

But this is not so important for now, could also stay as it is and we could discuss reasonable defaults for different situations as a follow-up.

File: spring-boot/admin/src/main/resources/application.yml (hunk 8 above)
Comment (gr-hovest-atb) [reply spring-boot/admin/src/main/resources/application.yml]: If I understand correctly, this is only used to delete the folder in local home? As I would advise against that, see other discussion, maybe we do not need this parameter at all.

The problem I see is simply: this parameter defines something that cannot be known.

File: README.md [hunk 34]
```diff
@@ -52,29 +56,27 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+
+* `build-and-push-images.sh` builds the docker image of each CoatRack modul from source and pushes the images to Dockerhub. This script shall only be used by the CI pipeline.
+* `build-and-deploy-images-locally.sh` builds CoatRack from source, creates container images on your local machine and runs CoatRack locally using these images. This is especially useful for developers who did changes to the source code and want to locally test the impact of these changes in a realistic setup.
 
-```console
-./run-admin-application.sh
-```
-After starting up, the CoatRack web application will be accessible at `http://localhost:8080` 
 
-*Optional:* If you are a CoatRack developer and want to run the application using a custom Spring profile, you can pass the profile name to the run script as follows:
```
Comment (gr-hovest-atb) [inline README.md:69]: This private profile information should not be deleted. Maybe it does not fit into this section, but in general we want to keep this information for developers. 

In doubt: create a follow-up issue as reminder to add this again in a later merge.

File: spring-boot/admin/src/main/resources/application.yml [hunk 35]
```diff
@@ -107,3 +126,12 @@ security:
       userInfoUri: https://api.github.com/user
 
 management.security.enabled: false
+
+# Proxy configuration files are stored in this directory. The value of this parameter needs to direct to the same
+# folder as spring.cloud.config.server.native.searchLocations from the Config Servers application.yml.
+proxy.config.files.folder: ${user.dir}/.temp-gateway-config-file-storage
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:132]: I am wondering: if I start-up admin and config server from different folders, wouldn't `user.dir` be different? On the other hand, this is maybe only relevant for local dev and thus not a problem?!

Another option would be to use a folder like `${user.home}/.coatrack/temp-gateway-config-file-storage`, which is independent of the folder from which admin/config-server have been started.

File: spring-boot/config-server/src/main/resources/application.yml [hunk 36]
```diff
@@ -7,31 +7,28 @@ logging:
...
+        properties:
+            hibernate:
+                format_sql: true
+        hibernate:
+            show-sql: true
+            generate-ddl: true
+            ddl-auto: create-drop
+            #ddl-auto: update
+    profiles.active: native
+    cloud.config.server.native.searchLocations: file:///${user.dir}/.temp-gateway-config-file-storage
```
Comment (gr-hovest-atb) [inline spring-boot/config-server/src/main/resources/application.yml:30]: Just as a reminder: We need to add this parameter to the Kubernetes deployment configurations.

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

File: docker/docker-compose-deployment/.env [hunk 37]
```diff
@@ -0,0 +1,23 @@
+COATRACK_VERSION=2.0.0-SNAPSHOT
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/docker-compose-deployment/.env:1]: If you use `docker-compose up` then there is no search in the `pom.xml`. The parameter is gained from the `.env` file. We can
1. keep it as it is and have a duplication or 
2. we could add another script which takes this `COATRACK_VERSION` from the `pom.xml` and then runs `docker-compose up`.

File: docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh [hunk 38]
```diff
@@ -0,0 +1,21 @@
+#!/bin/bash
+
+export PROJECT_DIR="${PWD}/.."
+export DOCKER_DIR="${PROJECT_DIR}/docker"
+export DOCKER_COMPOSE_DEPLOYMENT_DIR="${DOCKER_DIR}/docker-compose-deployment"
+
+cd "${DOCKER_COMPOSE_DEPLOYMENT_DIR}" || exit 1
+. stop-containers-and-clean-up-traces-if-existent.sh
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh:8]: This is correct. Therefore I added the "if-existent". When no containers are there, then the script continues with building and pushing the images.

File: docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh [hunk 39]
```diff
@@ -0,0 +1,21 @@
...
+
+cd "${PROJECT_DIR}" || exit 1
+export COATRACK_VERSION="$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
+printf "\nBuilding CoatRack module docker images.\n"
+echo "  Building jar files of CoatRack modules from source."
+mvn clean package -DskipTests jib:dockerBuild
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh:14]: Yes, it does.

File: spring-boot/admin/src/test/java/eu/coatrack/admin/model/repository/MetricsAggregationCustomRepositoryTest.java [hunk 40]
```diff
@@ -47,14 +47,7 @@
...
 
-    /**
-     * api provider username, needs to be in sync with sample data
-     *
-     * @see eu.coatrack.admin.DatabaseInitializer
-     */
-    @Value("${ygg.admin.database.sampleDataUsername:exampleCompanyInc}")
-    private String sampleDataApiProviderUsername;
-
+    private String sampleDataApiProviderUsername = "exampleCompanyInc";
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply spring-boot/admin/src/test/java/eu/coatrack/admin/model/repository/MetricsAggregationCustomRepositoryTest.java:50]: I don't know, this was just a possible explanation as far as I know. And yes, the change is required to get the testing working. Anyway, when I do the tests now, everything works. If the tests still happen to not behave deterministic, then, imo, we should remove or refactor the tests.

File: spring-boot/admin/src/main/resources/application.yml (hunk 35 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:132]: Ah sry, I forgot to mention that. I already tried out the `user.home` directory but this did not work out well. I think the reason is that the home is not equally defined in different environments. iirc, then using `user.home` did not work correctly in the CI pipeline (the CI runner to be precise) and failed.

File: spring-boot/config-server/src/main/resources/application.yml (hunk 36 above)
Comment (ChristophBaierATB) [reply spring-boot/config-server/src/main/resources/application.yml:30]: I made a note about that, so that we won't forget it.

File: README.md (hunk 34 above)
Comment (ChristophBaierATB) [reply README.md:69]: In created the follow-up issue #195.

**Comment by ChristophBaierATB** [comment]
@gr-hovest-atb this branch can now be re-reviewed by you. I will investigate the last, open TODO later but I expect it to cause just minor changes, if any.

File: README.md [hunk 41]
```diff
@@ -52,29 +56,27 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+* docker
+* docker-compose
+* OpenJDK 11
+* Maven 3.6.3 or higher
+
+
+
+There are two scripts in the `docker` directory helping you:
+
+* `build-and-push-images.sh` builds the docker image of each CoatRack modul from source and pushes the images to Dockerhub. This script shall only be used by the CI pipeline.
```
Comment (gr-hovest-atb) [inline README.md:75]:
```suggestion
* `build-and-push-images.sh` builds the docker image of each CoatRack module from source and pushes the images to Dockerhub. This script shall only be used by the CI pipeline.
```

File: spring-boot/admin/src/main/resources/application.yml [hunk 42]
```diff
@@ -107,3 +126,12 @@ security:
...
+
+# If CoatRack is deployed via IDE/commandline the Gateway config files will be stored in the '~/.coatrack' folder.
+# If docker-compose is used for deployment, these files will be stored internally within a docker volume by overrding
+# this parameter with 'false'.
+is-gateway-config-files-folder-in-users-home-directory: true
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml:137]: Two comments/questions:

1. Will it actually be stored in the home folder now? Or in the folder from where you start Coatrack? In another discussion you said that "user.home" does not work in the pipeline? 
2. In any case, the parameter name is misleading, as it defines what _should_ be done rather than what _is_ the case, so I would suggest to rename as an "instruction": `store-gateway-config-files-folder-in...directory`

**Review by gr-hovest-atb — APPROVED** [review]

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 1 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: I removed the folder deletion logic. 

Actually, you don't need a cleanup script. You can just delete the folder. On the next run of your application, a new and empty folder is created.

File: spring-boot/admin/src/main/resources/application.yml (hunk 8 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: I changed the overall logic a little bit. So you might want to take another look at it. The docker-compose.yml file provides an environment variable `IS_DEPLOYED_VIA_DOCKER_COMPOSE` for the JVM's of admin and config server. Admin and config-server check if this variable is set or not. Depending on that they 
1. either put the proxy jar and the proxy config files into docker volume folders
2. or use the local project folder to store/find these files.

File: spring-boot/admin/src/main/resources/application.yml (hunk 7 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Done. I just moved it to my private profile as suggested.

File: spring-boot/admin/src/main/resources/application.yml (hunk 5 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml:31]: On my TODO list.

File: spring-boot/admin/src/main/resources/application.yml (hunk 4 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Done.

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java (hunk 3 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/java/eu/coatrack/admin/service/GatewayConfigFilesStorage.java]: Good point. I applied your suggestion.

File: README.md [hunk 43]
```diff
@@ -84,18 +84,26 @@ The following prerequisites are required:
 
 
 
-Open a terminal, go into the `coatrack` directory, build all components and run the Web Application component (admin):
+Open a terminal, go into the `coatrack` directory and build all components using one the the commands below:
+
+```sh
+bash build.sh # For Linux shells
+mvn clean package # For Linux or Windows shells
```
Comment (gr-hovest-atb) [inline README.md:91]: I assume the `build.sh` does not work for windows? In this case it does not make sense to keep it here, as the second command should work for everyone...

File: README.md [hunk 44]
```diff
@@ -58,38 +58,77 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
 
- The following prerequisites are required:
+There are two tutorials inside the application:
+
+- Offering service APIs via CoatRack
+- Using service APIs offered via CoatRack
+
+
+
+## Install CoatRack Locally via CLI
```
Comment (gr-hovest-atb) [inline README.md:77]: As far as I understand the following instructions, they are to build from source and run locally. Therefore the word "Install" seems misleading to me. I would suggest to replace it by "Build and Run".

File: README.md [hunk 45]
```diff
@@ -58,38 +58,77 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
 
 
 
-## How to Build CoatRack Container Images from Source
+## Usage
+
+To start using CoatRack: 
+
+- either run CoatRack locally as explained in the "Install ..." sections
```
Comment (gr-hovest-atb) [inline README.md:65]: "Install" is misleading, see other comment below.

File: README.md [hunk 46]
```diff
@@ -58,38 +58,77 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+mvn clean package # For Linux or Windows shells
+```
 
+ 
 
+Run the Web Application component (admin):
 
-## Usage
+```sh
+java -jar spring-boot/admin/target/coatrack-admin-*.jar
```
Comment (gr-hovest-atb) [inline README.md:99]: We have the specific run script for this purpose, does it not work on Win? Maybe this should be solved in a follow-up.

File: README.md [hunk 47]
```diff
@@ -58,38 +58,77 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
-- Using service APIs offered via CoatRack
+```sh
+java -jar spring-boot/config-server/target/coatrack-config-server-*.jar
+```
+
+Now you a have a fully working instance of CoatRack using non-persistent databases. You can access it on `http://localhost:8080`.
+
+
+
+## Install CoatRack Locally via Docker Compose
```
Comment (gr-hovest-atb) [inline README.md:116]:
```suggestion
## Build and Run CoatRack Locally via Docker Compose
```

File: README.md [hunk 48]
```diff
@@ -58,38 +58,77 @@ The following figure shows the typical CoatRack architecture, the CoatRack web a
...
+* OpenJDK 11
+* Maven 3.6.3 or higher
+* docker 20.10.12 or higher
+* docker-compose 1.29.2 or higher
+
+
+
+With your terminal go into the `coatrack/docker` directory where you will find two scripts:
+
+* `build-and-push-images.sh` builds the docker image of each CoatRack module from source and pushes the images to Dockerhub. This script shall only be used by the CI pipeline.
```
Comment (gr-hovest-atb) [inline README.md:130]: This does not really fit in the section considering the heading "... Locally".

File: spring-boot/admin/src/main/java/eu/coatrack/admin/service/CustomProxyFileGeneratorService.java [hunk 49]
```diff
@@ -57,10 +55,6 @@ public class CustomProxyFileGeneratorService {
 
     private static final Logger log = LoggerFactory.getLogger(CustomProxyFileGeneratorService.class);
 
-    // ****************  Config Properties  ****************  
-    @Value("${ygg.proxy.executable-jar.template.url}")
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/java/eu/coatrack/admin/service/CustomProxyFileGeneratorService.java:61]: Why remove this configurable property? It was introduced to allow flexible configuration.

File: spring-boot/admin/src/main/resources/application.yml [hunk 50]
```diff
@@ -64,10 +63,6 @@ ygg:
   proxy:
     executable-jar:
       generated.path: /tmp
-      # URL of the "template jar" that CoatRack uses as basis to generate proxies.
-      # During development testing, this should usually point to your locally built coatrack gateway jar
-      # (but without the trailing version number and .jar filename extension, those will be added automatically).
-      template.url: file:///${user.dir}/spring-boot/proxy/target/coatrack-proxy-
```
Comment (gr-hovest-atb) [inline spring-boot/admin/src/main/resources/application.yml]: This should not be removed, it should stay configurable.

File: api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java [hunk 51]
```diff
@@ -0,0 +1,72 @@
...
+    public static final String GATEWAY_CONFIG_FILES_FOLDER_LOCATION;
+
+    static {
+        String isDeployedViaDockerCompose = System.getProperty("IS_DEPLOYED_VIA_DOCKER_COMPOSE");
+        if (isDeployedViaDockerCompose != null && isDeployedViaDockerCompose.equals("true")) {
+            GATEWAY_JAR_PATH_WITH_FILENAME_PREFIX = "file:///app/coatrack-proxy-";
+            GATEWAY_CONFIG_FILES_FOLDER_LOCATION = "/home/coatrack/gateway-config-files";
+        } else {
+            //Deployment is performed via CLI/IDE. The files are stored in/obtained from the coatrack project source folder.
+            GATEWAY_JAR_PATH_WITH_FILENAME_PREFIX = "file:///" + System.getProperty("user.dir") + "/spring-boot/proxy/target/coatrack-proxy-";
```
Comment (gr-hovest-atb) [inline api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java:50]: This should not be hard-coded, this should stay a config parameter.

File: api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java [hunk 52]
```diff
@@ -0,0 +1,72 @@
...
+
+    /**
+     * The Web Application (admin) should store and manage the gateway config files in this directory while the
+     * config-server reads them from there.
+     */
+    public static final String GATEWAY_CONFIG_FILES_FOLDER_LOCATION;
+
+    static {
+        String isDeployedViaDockerCompose = System.getProperty("IS_DEPLOYED_VIA_DOCKER_COMPOSE");
+        if (isDeployedViaDockerCompose != null && isDeployedViaDockerCompose.equals("true")) {
```
Comment (gr-hovest-atb) [inline api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java:45]: This if/else differentiates between "Docker Compose" and "CLI/IDE". Not sure: which of the options will/should be chosen when using Kubernetes deployment?

To make it more flexible, wouldn't it be easier to put these parameters into the config? Then the "CLI/IDE" parameters could be in the default `application.yml`, they could be overwritten via docker-compose file and also overwritten by Kubernetes config files.

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

**Comment by BrunoSilvaATB** [comment]
So @ChristophBaierATB I tested the whole functionality, trying to always follow your section (How to test this branch) in the description of this PR, and the results are the following:

- Building and Running Admin and Config Service are **working well** by using the `build.sh` and then just make a `java -jar` 

- All the parts for Building and creating docker containers (**worked well**), as you can see below:
image

image
One thing I really liked here, was the speed of creation of the gateway config, it was I clicked on the button to finish the Tutorial for Providers wizard, and as soon as I clicked on finish, I saw the busy icon for like 1 second (So this was extremely fast, well done @ChristophBaierATB)

Then I just download the gateway.jar, runned it by using CLI (`java -jar [proxy-name]`), called it via the link with the API Key, and it **worked well**:
image


- Now, about clicking on all the sidebar menu items on CoatRack admin, then 2 errors were found:
When trying to access the list of gateways page(**getting an error**):
image
image

About the Tutorial for consumer, so it seems that the docker network has no access to the raincoat service, which is used as example service for the tutorial for the consumer:
image

File: spring-boot/admin/src/main/resources/application.yml (hunk 8 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Deprecated.

File: spring-boot/admin/src/main/resources/application.yml (hunk 42 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Outdated.

File: api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java (hunk 51 above)
Comment (ChristophBaierATB) [reply api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java]: Outdated.

File: spring-boot/admin/src/main/resources/application.yml (hunk 50 above)
Comment (ChristophBaierATB) [reply spring-boot/admin/src/main/resources/application.yml]: Outdated.

File: api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java (hunk 52 above)
Comment (ChristophBaierATB) [reply api/src/main/java/eu/coatrack/config/DeploymentMethodDependentConfig.java]: Outdated.

**Review by gr-hovest-atb — APPROVED** [review]

File: README.md (hunk 44 above)
Comment (ChristophBaierATB) [reply README.md:77]: Done.

File: README.md (hunk 45 above)
Comment (ChristophBaierATB) [reply README.md:65]: Done as suggested in comment below.

File: README.md (hunk 47 above)
Comment (ChristophBaierATB) [reply README.md:109]: Done.

File: README.md (hunk 48 above)
Comment (ChristophBaierATB) [reply README.md]: I removed the script from this section, as it is just of interest for us developers.

**Comment by BrunoSilvaATB** [comment]
So it is now tested, and everything works

**Comment by BrunoSilvaATB** [comment]
> So @ChristophBaierATB I tested the whole functionality, trying to always follow your section (How to test this branch) in the description of this PR, and the results are the following:
> 
> * Building and Running Admin and Config Service are **working well** by using the `build.sh` and then just make a `java -jar`
> * All the parts for Building and creating docker containers (**worked well**), as you can see below:
>   image
> 
> image One thing I really liked here, was the speed of creation of the gateway config, it was I clicked on the button to finish the Tutorial for Providers wizard, and as soon as I clicked on finish, I saw the busy icon for like 1 second (So this was extremely fast, well done @ChristophBaierATB)
> 
> Then I just download the gateway.jar, runned it by using CLI (`java -jar [proxy-name]`), called it via the link with the API Key, and it **worked well**: image
> 
> * Now, about clicking on all the sidebar menu items on CoatRack admin, then 2 errors were found:
>   When trying to access the list of gateways page(**getting an error**):
>   image
>   image
> 
> About the Tutorial for consumer, so it seems that the docker network has no access to the raincoat service, which is used as example service for the tutorial for the consumer: image

The issues that occured here will be fixed on the issue #201

**Review by Monezz — APPROVED** [review]
