### PR TITLE
Bugfix/#237 Solved metrics day inconsistency bug

### LINKED ISSUE #237: Calls registered by Gateway appear "one day earlier" in Admin statistics
# Observed problem

**Please note**: This happens *if and only if* Gateway and Admin are running on machines with different timezones. It was observed when using the dockerized Coatrack version:
* CoatRack Admin was running in a container set to GMT timezone
* CoatRack Gateway was running on a machine with timezone set to GMT+2 (CEST).

The observed problem is: 

* Calls to the CoatRack Gateway are done **today**
* In the reports in CoatRack Admin, those calls show up (only) if we look at the report from **yesterday**

# Reason

After some investigation, the reason is as follows (in this example, "today" is the 13 October 2022):

* the Coatrack Gateway registers the call and stores today's date with the call, which is in this example: `2022-10-13` (no time information is stored)
* when sending to CoatRack Admin, this date of `2022-10-13` is encoded by the Gateway as `java.util.Date` with time set to "midnight", i.e. in this example `2022-10-13 00:00:00 CEST` 
* when it arrives at CoatRack Admin, this date is interpreted according to the Admin's timezone, which is GMT, so it becomes: `2022-10-12 22:00:00 GMT` 
* then it is stored in Admin's database without any time information, so it becomes `2022-10-12` in Admin`s DB

What the current implementation actually intended in the first place was that the local date of the Gateway would be relevant, this is why we store it without time or timezone information. But the problem is that the actual transfer between Gateway and Admin adds time(zone) information which is afterwards removed again.  

# To be discussed: 

* Does it make sense to change the related field in the CoatRack API from `java.util.Date` to `java.time.LocalDate`, so that the transfer between Gateway and Admin does not include timezone implications? What are the implications of changing the API that way?
* Besides, on a more general level: Who should "decide" about the date of the call? The timezone of the Gateway (imagine the Gateway is also dockerized and thus uses a different timezone)? The timezone of Admin?
* Or should we actually store the time(zone) info in the Admin database, not just the date? Then the display in the report would be adjusted to Admin timezone.

### PR DESCRIPTION
**Pull request by ChristophBaierATB**
Closes #237 

### Explanation of the Problem

I found the problem. The critical two lines are in the proxy module in the MetricsCounter class. One needs to know that there are two JDK classes Date:

    java.sql.date
    java.util.date

First critical snippet:
```java
.add(java.sql.Date.valueOf(LocalDate.now()).toString())
```
We use this snippet to generate a String like "2022-11-08" which remains the same for one day. This is necessary to build the same metric ID for two service requests that belong together. I just added java.sql. to make the difference clear between the two Date classes.

Second critical snippet:
```java
metricToTransmit.setDateOfApiCall(new java.util.Date());
```
We use java.util.date here, since it contains the time which is different for each request. We need this information to differentiate the two requests in the admin module.

### How to test this PR

The bug can be triggered by hand, when the time zone in `MetricsCounterService` class  is changed from "Europe/London" to a timezone in which it is still yesterday. For example, in Germany its currently 10:00 19th of January, while in "Pacific/Apia" it is 22:00. Now run set up CoatRack, e.g. via Docker Compose. If the Gateway sends data to the Web application, they should be visible in the Dashboard diagrams and the Report Table as if they arrived yesterday.

If you don't apply a timezone change and deploy CoatRack, the times should act normal.

### CODE REVIEW

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 1]
```diff
@@ -88,7 +88,7 @@ private String createCounterIdFromMetric(TemporaryMetricsAggregation tma) {
                 .add(tma.getApiKeyValue())
                 .add(tma.getMetricType().toString())
                 .add(String.valueOf(tma.getHttpResponseCode()))
-                .add(LocalDate.now().toString())
+                .add(java.sql.Date.valueOf(LocalDate.now()).toString())
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:91]: This change does not seem to have any effect on the String that is eventually created, or does it? If yes, please explain.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 2]
```diff
@@ -103,7 +103,7 @@ private Metric createMetricToTransmit(TemporaryMetricsAggregation tma) {
         metricToTransmit.setRequestMethod(tma.getRequestMethod());
         metricToTransmit.setType(tma.getMetricType());
         metricToTransmit.setHttpResponseCode(tma.getHttpResponseCode());
-        metricToTransmit.setDateOfApiCall(Date.valueOf(LocalDate.now()));
+        metricToTransmit.setDateOfApiCall(new java.util.Date());
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:106]: Although this solves the problem that most of the metrics are stored "with the wrong day" in admin, it still does not allow admin and gateway to run in different timezones. Consider the following situation with admin in UTC timezone and gateway in UTC+2:

- it is `2022-10-14 23:59 UTC` for admin and `2022-10-15 01:59 UTC+2` for the gateway
- the gateway is continuously counting calls for the date `2022-10-15` which are now 100 calls, however, as admin is still on the previous day, it stores `100th call at 2022-10-14`
- as soon as the admin time switches to `2022-10-15 00:00 UTC` and gateway time to  `2022-10-15 02:00 UTC+2`, the gateway registers the 101st call
- when gateway now sends the information `101st call at 2022-10-15 02:00 UTC+2` then admin will adjust it to its timezone and will store in the DB  `101st call at 2022-10-15`
- this means that admin now registered `100 calls on 2022-10-14` and `101 calls on 2022-10-15` although in reality it should have been `1 call on 2022-10-15`

Summarizing the problem: this solution lets "gateway count according to its timezone" while "admin stores the count according to another timezone". We need to discuss further how to solve this issue.

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 1 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: You are right. Therefore, I reverted that change.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 2 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:106]: I introduced a base image for the CoatRack components whose time zone is always CET. That means, currently, the system should work when the Gateway is deployed in a CET timezone. As this is meant to be a quick fix of the problem, this solution should suffice for now. We should create a follow-up issue within which the critical occurrences of `Date` will be replaced by `ZonedDateTime` and maybe implement a policy which handles all times uniformly in UTC. Would you agree?

Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: In addition, the Gateway also transmits metrics and date referring to CET timezone. The SIT's worked well, too. This solution should sufficient for a "quick fix". Please, have another look.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 3]
```diff
@@ -50,12 +52,18 @@ public class MetricsCounterService {
     public MetricsCounterService(MeterRegistry meterRegistry, MetricsTransmitter metricsTransmitter) {
         this.meterRegistry = meterRegistry;
         this.metricsTransmitter = metricsTransmitter;
+        // Quick fix of #237 by setting default time zones of Admin and Gateway to CET timezone.
+        // In the future, this system should be overhauled by the introduction of ZonedDateTime's.
+        TimeZone.setDefault(TimeZone.getTimeZone(ZoneId.of("Europe/Berlin")));
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:57]: If I understand [this article correctly](https://www.baeldung.com/java-jvm-time-zone), this command sets the timezone for the whole VM, not only for this class. Therefore it would be better to put it into the application's main class.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 4]
```diff
@@ -50,12 +52,18 @@ public class MetricsCounterService {
...
     }
 
     public void increment(TemporaryMetricsAggregation tma) {
         logBeginningOfIncrementation(tma);
-        int currentCount = incrementCounterAndReturnCurrentValue(tma);
-        Metric metricToTransmit = createMetricToTransmit(tma);
+
+        ZonedDateTime cetTimeNow = ZonedDateTime.now(ZoneId.of("Europe/Berlin"));
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:63]: As the JVM time was already set to `CET`, it seems there is no need to set the timezone again here?!

Besides, as neither gateway nor admin actually use the time information, I assume that `LocalDate.now()` should be sufficient here.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 5]
```diff
@@ -80,20 +88,20 @@ private int incrementCounterAndReturnCurrentValue(TemporaryMetricsAggregation tm
...
+    private String createCounterIdFromMetric(TemporaryMetricsAggregation tma, ZonedDateTime cetTimeNow) {
         StringJoiner stringJoiner = new StringJoiner(SEPARATOR);
         stringJoiner.add(PREFIX)
                 .add(tma.getServiceApiName())
                 .add(tma.getRequestMethod())
                 .add(tma.getApiKeyValue())
                 .add(tma.getMetricType().toString())
                 .add(String.valueOf(tma.getHttpResponseCode()))
-                .add(LocalDate.now().toString())
+                .add(java.sql.Date.valueOf(cetTimeNow.toLocalDate()).toString())
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:99]: The `java.sql.Date.valueOf()` seems to be not required.

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 6]
```diff
@@ -103,7 +111,7 @@ private Metric createMetricToTransmit(TemporaryMetricsAggregation tma) {
         metricToTransmit.setRequestMethod(tma.getRequestMethod());
         metricToTransmit.setType(tma.getMetricType());
         metricToTransmit.setHttpResponseCode(tma.getHttpResponseCode());
-        metricToTransmit.setDateOfApiCall(Date.valueOf(LocalDate.now()));
+        metricToTransmit.setDateOfApiCall(java.util.Date.from(cetTimeNow.toInstant()));
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:114]: The previous code was setting just the date, meaning that the time was always set as `00:00:00`. The new code sets the current time instead. However, as on admin side just the date is stored in the DB, there seems to be now improvement when sending the current time.

File: docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh [hunk 7]
```diff
@@ -7,6 +7,12 @@ export DOCKER_COMPOSE_DEPLOYMENT_DIR="${DOCKER_DIR}/docker-compose-deployment"
 cd "${DOCKER_COMPOSE_DEPLOYMENT_DIR}" || exit 1
 . stop-containers-and-clean-up-traces-if-existent.sh
 
+echo "  Building Docker base image."
+cd "$DOCKER_DIR" || exit 1
+if ! docker images | grep jre11-alpine-timezone-cet > /dev/null; then
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh]: I simplified the code and this code change was removed. Therefore this thread can be closed.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 3 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: When we change the metrics logic (e.g. by replacing it with Micrometer) then this class is removed and `TimeZone.setDefault(...)` is not required anymore. Since this command and the `MetricsCounterService` class belong together, I'd prefer to keep them in the same class.

File: docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh [hunk 8]
```diff
@@ -7,6 +7,12 @@ export DOCKER_COMPOSE_DEPLOYMENT_DIR="${DOCKER_DIR}/docker-compose-deployment"
 cd "${DOCKER_COMPOSE_DEPLOYMENT_DIR}" || exit 1
 . stop-containers-and-clean-up-traces-if-existent.sh
 
+echo "  Building Docker base image."
```
[the remark this answers is not in the document]
Comment (ChristophBaierATB) [reply docker/helper-script-building-the-docker-images-and-exporting-environment-variables.sh]: I simplified the code and this code change was removed. Therefore this thread can be closed.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 2 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: Update: I could drastically simplify this PR by making all components use UTC  instead of CET now.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 5 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: Correct. I removed it.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 6 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: The problem here is that this could lead to bugs. With the old approach we are generating two time at different moments in the logic. It might be unlikely, but if one time is taken just before midnight and the other time just after midnight, we would have a time inconsistency problem which generates wrong metrics.

In my new approach, I take a time only once and derive any subsequent time information from it.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 4 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: You are right. `LocalDate now = LocalDate.now()` is sufficient here. However, transforming it to a Date, the Timezone has to be provided, too:
```
java.util.Date.from(now.atStartOfDay().toInstant(ZoneOffset.UTC))
```

**Comment by ChristophBaierATB** [comment]
@gr-hovest-atb Update: I could drastically simplify this PR by making all components use UTC instead of CET now.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 9]
```diff
@@ -28,15 +28,21 @@
...
 import java.util.StringJoiner;
+import java.util.TimeZone;
 import java.util.UUID;
 
 import eu.coatrack.api.ApiKey;
 
 @Service
 public class MetricsCounterService {
 
+    // Quick fix of #237 by setting default time zones of Admin and Gateway to UCT timezone.
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:41]: This pull request changes only sets the Gateway timezone, but according to this comment it should also set the Admin timezone.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 10]
```diff
@@ -28,15 +28,21 @@
...
+    // In the future, this system should be overhauled by the introduction of ZonedDateTime's.
+    static {
+        TimeZone.setDefault(TimeZone.getTimeZone(ZoneId.of("Europe/London")));
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:44]: London time is not always equal to UTC, see https://en.wikipedia.org/wiki/British_Summer_Time

So it should probably be:
```suggestion
        TimeZone.setDefault(TimeZone.getTimeZone(ZoneId.of("UTC")));
```

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 11]
```diff
@@ -54,8 +60,11 @@ public MetricsCounterService(MeterRegistry meterRegistry, MetricsTransmitter met
 
     public void increment(TemporaryMetricsAggregation tma) {
         logBeginningOfIncrementation(tma);
-        int currentCount = incrementCounterAndReturnCurrentValue(tma);
-        Metric metricToTransmit = createMetricToTransmit(tma);
+
+        LocalDate now = LocalDate.now();
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:64]: Maybe it would be more clear to call the variable `today`, as it does not contain any time information.

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java [hunk 12]
```diff
@@ -103,7 +112,7 @@ private Metric createMetricToTransmit(TemporaryMetricsAggregation tma) {
         metricToTransmit.setRequestMethod(tma.getRequestMethod());
         metricToTransmit.setType(tma.getMetricType());
         metricToTransmit.setHttpResponseCode(tma.getHttpResponseCode());
-        metricToTransmit.setDateOfApiCall(Date.valueOf(LocalDate.now()));
+        metricToTransmit.setDateOfApiCall(java.util.Date.from(now.atStartOfDay().toInstant(ZoneOffset.UTC)));
```
Comment (gr-hovest-atb) [inline spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java:115]: This change seems to have no effect at all. Due to the UTC timezone set for the whole VM, the parameter `now` is already the current date according to UTC. The following would thus easier to read (also considering that the `now` parameter does not contain time information so maybe `today` seems to be a better name):

```
private Metric createMetricToTransmit(TemporaryMetricsAggregation tma, LocalDate today {
[...]
metricToTransmit.setDateOfApiCall(Date.valueOf(today));
```

**Review by gr-hovest-atb — CHANGES_REQUESTED** [review]

File: spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java (hunk 12 above)
Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: Ah sry, I think I delivered the wrong explanation.

In the previous approach, to create a metric we constructed two time objects with a little processing in between. When the times are created before and after midnight (which is a rare but possible case), this would result in a different dates and therefore inconsistencies. 

In the current approach a `LocalDate today` is created once an delivered as argument two times. Therefore, this inconsistency problem can't happen anymore.

So this "hacky" expression solves is the transformation of `LocalDate today` from the argument to a Date, see [here](https://beginnersbook.com/2017/10/java-convert-localdate-to-date/).

Comment (ChristophBaierATB) [reply spring-boot/proxy/src/main/java/eu/coatrack/proxy/metrics/MetricsCounterService.java]: After re-thinking the matter, I agree. Done as suggested.

**Comment by BrunoSilvaATB** [comment]
**Report on testing**:

I tested this branch with maven/inteliJ (so no Docker(, and these are the results:

1. The admin is indeed working in UTC time now:
AdminUTCTime

2. I created a gateway, and made and call. and the response is the correct date of the call and in a simplified way:
image

3. I changed the timezone of the Gateway to Sydney/Australia, as it is already friday, there and indeed the admin got tomorrow's data
image
And if looking at the reports, the admin still counts as today, as it is still in UTC
image

Based on this, I would say that this works already with Maven/IntelliJ; and I tested previously with Docker, so I would say that it works correctly too.

**Review by gr-hovest-atb — APPROVED** [review]

**Review by BrunoSilvaATB — APPROVED** [review]
I tested it, and it worked well. The tests are reported [here](https://github.com/coatrack/coatrack/pull/240#issuecomment-1405049485)

**Review by monezz — APPROVED** [review]
